config/routes.rb
Rails.application.routes.draw do
 resources :worlds

end

app/models/world.rb
class World < ActiveRecord::Base
	validates_presence_of :title, :description
	validates_uniqueness_of :title
	validates_length_of :description, minimum: 10

	before_save :switch_case

	private

	def switch_case
		self.title.downcase!
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/worlds_controller.rb
class WorldsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end
  
  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/worlds_helper.rb
module WorldsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DicadmAppV1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/worlds/edit.html.erb
edit.html.erb

app/views/worlds/index.html.erb
<h1>Worlds#index</h1>
<p>Find me in app/views/worlds/index.html.erb</p>

<%= link_to "New world", new_world_path %>

app/views/worlds/new.html.erb
new.html.erb

app/views/worlds/show.html.erb
show.html.erb